# Generated by Django 3.2.12 on 2022-05-12 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 13, 28, 54, 251694, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
